dia = input ('Digite o dia do seu nascimento => ')
mes = input ('Digite o mes do seu nascimento => ')
ano = input ('Digite o ano do seu nascimento => ')
print ('Voce nasceu no dia' , dia , 'de' , mes , 'de' , ano , 'correto?')
nada = input ('')
