x = input("Digite algo: ")
print('O tipo primitivo desse valor é :', type(x))
print('Só foi digitado espaço? ', x.isspace())
print('É um numero? ', x.isnumeric())
print('É alfabetico?  ', x.isalpha())
print('É alfanumerico?  ', x.isalnum())
print('Esta em maiusculo?  ', x.isupper())
print('Esta em minusculo?  ', x.islower())
print('Esta capitalizada?  ', x.istitle())

